# Generated by Django 5.0.2 on 2024-03-01 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_hebergement', models.CharField(choices=[('HO', 'Hôtel'), ('AU', 'Auberge'), ('CH', "Chambre d'hôte")], max_length=2)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_chambres_disponibles', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='description',
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.voyage'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hebergement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.hebergement'),
        ),
        migrations.DeleteModel(
            name='Itineraire',
        ),
    ]
